#!/usr/bin/env bash
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

frameworkVersion=net46
netfx=${frameworkVersion#net}

echo "[INFO] Target framework: ${frameworkVersion}"

echo "[INFO] Download nuget and packages"
wget -nc https://dist.nuget.org/win-x86-commandline/v4.5.0/nuget.exe
mozroots --import --sync
mono nuget.exe install src/Tradovate.Services/packages.config -o packages;

echo "[INFO] Copy DLLs to the 'bin' folder"
mkdir -p bin;
cp packages/Newtonsoft.Json.10.0.3/lib/net45/Newtonsoft.Json.dll bin/Newtonsoft.Json.dll;
cp packages/RestSharp.105.2.2/lib/net46/RestSharp.dll bin/RestSharp.dll;
cp packages/Websocket4Net.0.15.1/lib/net45/Websocket4Net.dll bin/Websocket4Net.dll;
cp packages/SuperSocket.ClientEngine.Core.0.9.0/lib/net45/SuperSocket.ClientEngine.dll bin/SuperSocket.ClientEngine.dll

echo "[INFO] Run 'mcs' to build bin/Tradovate.Services.dll"
mcs -sdk:${netfx} -r:bin/Newtonsoft.Json.dll,\
bin/RestSharp.dll,\
bin/Websocket4Net.dll,\
bin/SuperSocket.ClientEngine.dll,\
System.Runtime.Serialization.dll,\
System.ComponentModel.DataAnnotations.dll \
-target:library \
-out:bin/Tradovate.Services.dll \
-recurse:'src/Tradovate.Services/*.cs' \
-doc:bin/Tradovate.Services.xml \
-platform:anycpu

if [ $? -ne 0 ]
then
  echo "[ERROR] Compilation failed with exit code $?"
  exit 1
else
  echo "[INFO] bin/Tradovate.Services.dll was created successfully"
fi
