/* 
 * Tradovate API
 *
 * Tradovate API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Tradovate.Services.Model
{
    /// <summary>
    /// MarkReadAlertSignal
    /// </summary>
    [DataContract]
    public partial class MarkReadAlertSignal :  IEquatable<MarkReadAlertSignal>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MarkReadAlertSignal" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MarkReadAlertSignal() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MarkReadAlertSignal" /> class.
        /// </summary>
        /// <param name="AlertId">id of Alert (required).</param>
        /// <param name="AlertSignalId">id of AlertSignal (required).</param>
        public MarkReadAlertSignal(int? AlertId = null, int? AlertSignalId = null)
        {
            // to ensure "AlertId" is required (not null)
            if (AlertId == null)
            {
                throw new InvalidDataException("AlertId is a required property for MarkReadAlertSignal and cannot be null");
            }
            else
            {
                this.AlertId = AlertId;
            }
            // to ensure "AlertSignalId" is required (not null)
            if (AlertSignalId == null)
            {
                throw new InvalidDataException("AlertSignalId is a required property for MarkReadAlertSignal and cannot be null");
            }
            else
            {
                this.AlertSignalId = AlertSignalId;
            }
        }
        
        /// <summary>
        /// id of Alert
        /// </summary>
        /// <value>id of Alert</value>
        [DataMember(Name="alertId", EmitDefaultValue=false)]
        public int? AlertId { get; set; }
        /// <summary>
        /// id of AlertSignal
        /// </summary>
        /// <value>id of AlertSignal</value>
        [DataMember(Name="alertSignalId", EmitDefaultValue=false)]
        public int? AlertSignalId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MarkReadAlertSignal {\n");
            sb.Append("  AlertId: ").Append(AlertId).Append("\n");
            sb.Append("  AlertSignalId: ").Append(AlertSignalId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as MarkReadAlertSignal);
        }

        /// <summary>
        /// Returns true if MarkReadAlertSignal instances are equal
        /// </summary>
        /// <param name="other">Instance of MarkReadAlertSignal to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MarkReadAlertSignal other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AlertId == other.AlertId ||
                    this.AlertId != null &&
                    this.AlertId.Equals(other.AlertId)
                ) && 
                (
                    this.AlertSignalId == other.AlertSignalId ||
                    this.AlertSignalId != null &&
                    this.AlertSignalId.Equals(other.AlertSignalId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AlertId != null)
                    hash = hash * 59 + this.AlertId.GetHashCode();
                if (this.AlertSignalId != null)
                    hash = hash * 59 + this.AlertSignalId.GetHashCode();
                return hash;
            }
        }
    }

}
