/* 
 * Tradovate API
 *
 * Tradovate API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Tradovate.Services.Model
{
    /// <summary>
    /// MarkAsReadChatMessage
    /// </summary>
    [DataContract]
    public partial class MarkAsReadChatMessage :  IEquatable<MarkAsReadChatMessage>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MarkAsReadChatMessage" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MarkAsReadChatMessage() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MarkAsReadChatMessage" /> class.
        /// </summary>
        /// <param name="ChatMessageId">id of ChatMessage (required).</param>
        public MarkAsReadChatMessage(int? ChatMessageId = null)
        {
            // to ensure "ChatMessageId" is required (not null)
            if (ChatMessageId == null)
            {
                throw new InvalidDataException("ChatMessageId is a required property for MarkAsReadChatMessage and cannot be null");
            }
            else
            {
                this.ChatMessageId = ChatMessageId;
            }
        }
        
        /// <summary>
        /// id of ChatMessage
        /// </summary>
        /// <value>id of ChatMessage</value>
        [DataMember(Name="chatMessageId", EmitDefaultValue=false)]
        public int? ChatMessageId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MarkAsReadChatMessage {\n");
            sb.Append("  ChatMessageId: ").Append(ChatMessageId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as MarkAsReadChatMessage);
        }

        /// <summary>
        /// Returns true if MarkAsReadChatMessage instances are equal
        /// </summary>
        /// <param name="other">Instance of MarkAsReadChatMessage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MarkAsReadChatMessage other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ChatMessageId == other.ChatMessageId ||
                    this.ChatMessageId != null &&
                    this.ChatMessageId.Equals(other.ChatMessageId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ChatMessageId != null)
                    hash = hash * 59 + this.ChatMessageId.GetHashCode();
                return hash;
            }
        }
    }

}
