/* 
 * Tradovate API
 *
 * Tradovate API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Tradovate.Services.Model
{
    /// <summary>
    /// RollContract
    /// </summary>
    [DataContract]
    public partial class RollContract :  IEquatable<RollContract>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RollContract" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RollContract() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RollContract" /> class.
        /// </summary>
        /// <param name="Name">Name (required).</param>
        /// <param name="Forward">Forward (required).</param>
        /// <param name="IfExpired">IfExpired.</param>
        public RollContract(string Name = null, bool? Forward = null, bool? IfExpired = null)
        {
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for RollContract and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            // to ensure "Forward" is required (not null)
            if (Forward == null)
            {
                throw new InvalidDataException("Forward is a required property for RollContract and cannot be null");
            }
            else
            {
                this.Forward = Forward;
            }
            this.IfExpired = IfExpired;
        }
        
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Gets or Sets Forward
        /// </summary>
        [DataMember(Name="forward", EmitDefaultValue=false)]
        public bool? Forward { get; set; }
        /// <summary>
        /// Gets or Sets IfExpired
        /// </summary>
        [DataMember(Name="ifExpired", EmitDefaultValue=false)]
        public bool? IfExpired { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RollContract {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Forward: ").Append(Forward).Append("\n");
            sb.Append("  IfExpired: ").Append(IfExpired).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as RollContract);
        }

        /// <summary>
        /// Returns true if RollContract instances are equal
        /// </summary>
        /// <param name="other">Instance of RollContract to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RollContract other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.Forward == other.Forward ||
                    this.Forward != null &&
                    this.Forward.Equals(other.Forward)
                ) && 
                (
                    this.IfExpired == other.IfExpired ||
                    this.IfExpired != null &&
                    this.IfExpired.Equals(other.IfExpired)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.Forward != null)
                    hash = hash * 59 + this.Forward.GetHashCode();
                if (this.IfExpired != null)
                    hash = hash * 59 + this.IfExpired.GetHashCode();
                return hash;
            }
        }
    }

}
