/* 
 * Tradovate API
 *
 * Tradovate API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Tradovate.Services.Model
{
    /// <summary>
    /// SignUpResponse
    /// </summary>
    [DataContract]
    public partial class SignUpResponse :  IEquatable<SignUpResponse>
    {
        /// <summary>
        /// DataError, EmailAlreadyRegistered, EmailPolicyFailed, FailedRecaptcha, Success, UnknownError, UserAlreadyExists, WeakPassword, WrongChallenge, WrongChallengeOrigin
        /// </summary>
        /// <value>DataError, EmailAlreadyRegistered, EmailPolicyFailed, FailedRecaptcha, Success, UnknownError, UserAlreadyExists, WeakPassword, WrongChallenge, WrongChallengeOrigin</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ErrorCodeEnum
        {
            
            /// <summary>
            /// Enum DataError for "DataError"
            /// </summary>
            [EnumMember(Value = "DataError")]
            DataError,
            
            /// <summary>
            /// Enum EmailAlreadyRegistered for "EmailAlreadyRegistered"
            /// </summary>
            [EnumMember(Value = "EmailAlreadyRegistered")]
            EmailAlreadyRegistered,
            
            /// <summary>
            /// Enum EmailPolicyFailed for "EmailPolicyFailed"
            /// </summary>
            [EnumMember(Value = "EmailPolicyFailed")]
            EmailPolicyFailed,
            
            /// <summary>
            /// Enum FailedRecaptcha for "FailedRecaptcha"
            /// </summary>
            [EnumMember(Value = "FailedRecaptcha")]
            FailedRecaptcha,
            
            /// <summary>
            /// Enum Success for "Success"
            /// </summary>
            [EnumMember(Value = "Success")]
            Success,
            
            /// <summary>
            /// Enum UnknownError for "UnknownError"
            /// </summary>
            [EnumMember(Value = "UnknownError")]
            UnknownError,
            
            /// <summary>
            /// Enum UserAlreadyExists for "UserAlreadyExists"
            /// </summary>
            [EnumMember(Value = "UserAlreadyExists")]
            UserAlreadyExists,
            
            /// <summary>
            /// Enum WeakPassword for "WeakPassword"
            /// </summary>
            [EnumMember(Value = "WeakPassword")]
            WeakPassword,
            
            /// <summary>
            /// Enum WrongChallenge for "WrongChallenge"
            /// </summary>
            [EnumMember(Value = "WrongChallenge")]
            WrongChallenge,
            
            /// <summary>
            /// Enum WrongChallengeOrigin for "WrongChallengeOrigin"
            /// </summary>
            [EnumMember(Value = "WrongChallengeOrigin")]
            WrongChallengeOrigin
        }

        /// <summary>
        /// DataError, EmailAlreadyRegistered, EmailPolicyFailed, FailedRecaptcha, Success, UnknownError, UserAlreadyExists, WeakPassword, WrongChallenge, WrongChallengeOrigin
        /// </summary>
        /// <value>DataError, EmailAlreadyRegistered, EmailPolicyFailed, FailedRecaptcha, Success, UnknownError, UserAlreadyExists, WeakPassword, WrongChallenge, WrongChallengeOrigin</value>
        [DataMember(Name="errorCode", EmitDefaultValue=false)]
        public ErrorCodeEnum? ErrorCode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SignUpResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SignUpResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SignUpResponse" /> class.
        /// </summary>
        /// <param name="ErrorText">Non-empty if the request failed.</param>
        /// <param name="ErrorCode">DataError, EmailAlreadyRegistered, EmailPolicyFailed, FailedRecaptcha, Success, UnknownError, UserAlreadyExists, WeakPassword, WrongChallenge, WrongChallengeOrigin (required).</param>
        /// <param name="UserId">id of User.</param>
        /// <param name="EmailVerified">EmailVerified (required).</param>
        public SignUpResponse(string ErrorText = null, ErrorCodeEnum? ErrorCode = null, int? UserId = null, bool? EmailVerified = null)
        {
            // to ensure "ErrorCode" is required (not null)
            if (ErrorCode == null)
            {
                throw new InvalidDataException("ErrorCode is a required property for SignUpResponse and cannot be null");
            }
            else
            {
                this.ErrorCode = ErrorCode;
            }
            // to ensure "EmailVerified" is required (not null)
            if (EmailVerified == null)
            {
                throw new InvalidDataException("EmailVerified is a required property for SignUpResponse and cannot be null");
            }
            else
            {
                this.EmailVerified = EmailVerified;
            }
            this.ErrorText = ErrorText;
            this.UserId = UserId;
        }
        
        /// <summary>
        /// Non-empty if the request failed
        /// </summary>
        /// <value>Non-empty if the request failed</value>
        [DataMember(Name="errorText", EmitDefaultValue=false)]
        public string ErrorText { get; set; }
        /// <summary>
        /// id of User
        /// </summary>
        /// <value>id of User</value>
        [DataMember(Name="userId", EmitDefaultValue=false)]
        public int? UserId { get; set; }
        /// <summary>
        /// Gets or Sets EmailVerified
        /// </summary>
        [DataMember(Name="emailVerified", EmitDefaultValue=false)]
        public bool? EmailVerified { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SignUpResponse {\n");
            sb.Append("  ErrorText: ").Append(ErrorText).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  EmailVerified: ").Append(EmailVerified).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SignUpResponse);
        }

        /// <summary>
        /// Returns true if SignUpResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of SignUpResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SignUpResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ErrorText == other.ErrorText ||
                    this.ErrorText != null &&
                    this.ErrorText.Equals(other.ErrorText)
                ) && 
                (
                    this.ErrorCode == other.ErrorCode ||
                    this.ErrorCode != null &&
                    this.ErrorCode.Equals(other.ErrorCode)
                ) && 
                (
                    this.UserId == other.UserId ||
                    this.UserId != null &&
                    this.UserId.Equals(other.UserId)
                ) && 
                (
                    this.EmailVerified == other.EmailVerified ||
                    this.EmailVerified != null &&
                    this.EmailVerified.Equals(other.EmailVerified)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ErrorText != null)
                    hash = hash * 59 + this.ErrorText.GetHashCode();
                if (this.ErrorCode != null)
                    hash = hash * 59 + this.ErrorCode.GetHashCode();
                if (this.UserId != null)
                    hash = hash * 59 + this.UserId.GetHashCode();
                if (this.EmailVerified != null)
                    hash = hash * 59 + this.EmailVerified.GetHashCode();
                return hash;
            }
        }
    }

}
