/* 
 * Tradovate API
 *
 * Tradovate API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Tradovate.Services.Model
{
    /// <summary>
    /// StartOrderStrategy
    /// </summary>
    [DataContract]
    public partial class StartOrderStrategy :  IEquatable<StartOrderStrategy>
    {
        /// <summary>
        /// Buy, Sell
        /// </summary>
        /// <value>Buy, Sell</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ActionEnum
        {
            
            /// <summary>
            /// Enum Buy for "Buy"
            /// </summary>
            [EnumMember(Value = "Buy")]
            Buy,
            
            /// <summary>
            /// Enum Sell for "Sell"
            /// </summary>
            [EnumMember(Value = "Sell")]
            Sell
        }

        /// <summary>
        /// Buy, Sell
        /// </summary>
        /// <value>Buy, Sell</value>
        [DataMember(Name="action", EmitDefaultValue=false)]
        public ActionEnum? Action { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="StartOrderStrategy" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StartOrderStrategy() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StartOrderStrategy" /> class.
        /// </summary>
        /// <param name="AccountId">id of Account.</param>
        /// <param name="AccountSpec">AccountSpec.</param>
        /// <param name="Symbol">Symbol (required).</param>
        /// <param name="OrderStrategyTypeId">id of OrderStrategyType (required).</param>
        /// <param name="Action">Buy, Sell (required).</param>
        /// <param name="_Params">_Params.</param>
        /// <param name="Uuid">Uuid.</param>
        /// <param name="CustomTag50">CustomTag50.</param>
        public StartOrderStrategy(int? AccountId = null, string AccountSpec = null, string Symbol = null, int? OrderStrategyTypeId = null, ActionEnum? Action = null, string _Params = null, string Uuid = null, string CustomTag50 = null)
        {
            // to ensure "Symbol" is required (not null)
            if (Symbol == null)
            {
                throw new InvalidDataException("Symbol is a required property for StartOrderStrategy and cannot be null");
            }
            else
            {
                this.Symbol = Symbol;
            }
            // to ensure "OrderStrategyTypeId" is required (not null)
            if (OrderStrategyTypeId == null)
            {
                throw new InvalidDataException("OrderStrategyTypeId is a required property for StartOrderStrategy and cannot be null");
            }
            else
            {
                this.OrderStrategyTypeId = OrderStrategyTypeId;
            }
            // to ensure "Action" is required (not null)
            if (Action == null)
            {
                throw new InvalidDataException("Action is a required property for StartOrderStrategy and cannot be null");
            }
            else
            {
                this.Action = Action;
            }
            this.AccountId = AccountId;
            this.AccountSpec = AccountSpec;
            this._Params = _Params;
            this.Uuid = Uuid;
            this.CustomTag50 = CustomTag50;
        }
        
        /// <summary>
        /// id of Account
        /// </summary>
        /// <value>id of Account</value>
        [DataMember(Name="accountId", EmitDefaultValue=false)]
        public int? AccountId { get; set; }
        /// <summary>
        /// Gets or Sets AccountSpec
        /// </summary>
        [DataMember(Name="accountSpec", EmitDefaultValue=false)]
        public string AccountSpec { get; set; }
        /// <summary>
        /// Gets or Sets Symbol
        /// </summary>
        [DataMember(Name="symbol", EmitDefaultValue=false)]
        public string Symbol { get; set; }
        /// <summary>
        /// id of OrderStrategyType
        /// </summary>
        /// <value>id of OrderStrategyType</value>
        [DataMember(Name="orderStrategyTypeId", EmitDefaultValue=false)]
        public int? OrderStrategyTypeId { get; set; }
        /// <summary>
        /// Gets or Sets _Params
        /// </summary>
        [DataMember(Name="params", EmitDefaultValue=false)]
        public string _Params { get; set; }
        /// <summary>
        /// Gets or Sets Uuid
        /// </summary>
        [DataMember(Name="uuid", EmitDefaultValue=false)]
        public string Uuid { get; set; }
        /// <summary>
        /// Gets or Sets CustomTag50
        /// </summary>
        [DataMember(Name="customTag50", EmitDefaultValue=false)]
        public string CustomTag50 { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StartOrderStrategy {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  AccountSpec: ").Append(AccountSpec).Append("\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  OrderStrategyTypeId: ").Append(OrderStrategyTypeId).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  _Params: ").Append(_Params).Append("\n");
            sb.Append("  Uuid: ").Append(Uuid).Append("\n");
            sb.Append("  CustomTag50: ").Append(CustomTag50).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as StartOrderStrategy);
        }

        /// <summary>
        /// Returns true if StartOrderStrategy instances are equal
        /// </summary>
        /// <param name="other">Instance of StartOrderStrategy to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StartOrderStrategy other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AccountId == other.AccountId ||
                    this.AccountId != null &&
                    this.AccountId.Equals(other.AccountId)
                ) && 
                (
                    this.AccountSpec == other.AccountSpec ||
                    this.AccountSpec != null &&
                    this.AccountSpec.Equals(other.AccountSpec)
                ) && 
                (
                    this.Symbol == other.Symbol ||
                    this.Symbol != null &&
                    this.Symbol.Equals(other.Symbol)
                ) && 
                (
                    this.OrderStrategyTypeId == other.OrderStrategyTypeId ||
                    this.OrderStrategyTypeId != null &&
                    this.OrderStrategyTypeId.Equals(other.OrderStrategyTypeId)
                ) && 
                (
                    this.Action == other.Action ||
                    this.Action != null &&
                    this.Action.Equals(other.Action)
                ) && 
                (
                    this._Params == other._Params ||
                    this._Params != null &&
                    this._Params.Equals(other._Params)
                ) && 
                (
                    this.Uuid == other.Uuid ||
                    this.Uuid != null &&
                    this.Uuid.Equals(other.Uuid)
                ) && 
                (
                    this.CustomTag50 == other.CustomTag50 ||
                    this.CustomTag50 != null &&
                    this.CustomTag50.Equals(other.CustomTag50)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AccountId != null)
                    hash = hash * 59 + this.AccountId.GetHashCode();
                if (this.AccountSpec != null)
                    hash = hash * 59 + this.AccountSpec.GetHashCode();
                if (this.Symbol != null)
                    hash = hash * 59 + this.Symbol.GetHashCode();
                if (this.OrderStrategyTypeId != null)
                    hash = hash * 59 + this.OrderStrategyTypeId.GetHashCode();
                if (this.Action != null)
                    hash = hash * 59 + this.Action.GetHashCode();
                if (this._Params != null)
                    hash = hash * 59 + this._Params.GetHashCode();
                if (this.Uuid != null)
                    hash = hash * 59 + this.Uuid.GetHashCode();
                if (this.CustomTag50 != null)
                    hash = hash * 59 + this.CustomTag50.GetHashCode();
                return hash;
            }
        }
    }

}
