/* 
 * Tradovate API
 *
 * Tradovate API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Tradovate.Services.Model
{
    /// <summary>
    /// UserSessionStats
    /// </summary>
    [DataContract]
    public partial class UserSessionStats :  IEquatable<UserSessionStats>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserSessionStats" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserSessionStats() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserSessionStats" /> class.
        /// </summary>
        /// <param name="Id">Id.</param>
        /// <param name="LastSessionTime">LastSessionTime (required).</param>
        /// <param name="FailedPasswords">FailedPasswords (required).</param>
        public UserSessionStats(int? Id = null, DateTime? LastSessionTime = null, int? FailedPasswords = null)
        {
            // to ensure "LastSessionTime" is required (not null)
            if (LastSessionTime == null)
            {
                throw new InvalidDataException("LastSessionTime is a required property for UserSessionStats and cannot be null");
            }
            else
            {
                this.LastSessionTime = LastSessionTime;
            }
            // to ensure "FailedPasswords" is required (not null)
            if (FailedPasswords == null)
            {
                throw new InvalidDataException("FailedPasswords is a required property for UserSessionStats and cannot be null");
            }
            else
            {
                this.FailedPasswords = FailedPasswords;
            }
            this.Id = Id;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }
        /// <summary>
        /// Gets or Sets LastSessionTime
        /// </summary>
        [DataMember(Name="lastSessionTime", EmitDefaultValue=false)]
        public DateTime? LastSessionTime { get; set; }
        /// <summary>
        /// Gets or Sets FailedPasswords
        /// </summary>
        [DataMember(Name="failedPasswords", EmitDefaultValue=false)]
        public int? FailedPasswords { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserSessionStats {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LastSessionTime: ").Append(LastSessionTime).Append("\n");
            sb.Append("  FailedPasswords: ").Append(FailedPasswords).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as UserSessionStats);
        }

        /// <summary>
        /// Returns true if UserSessionStats instances are equal
        /// </summary>
        /// <param name="other">Instance of UserSessionStats to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserSessionStats other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.LastSessionTime == other.LastSessionTime ||
                    this.LastSessionTime != null &&
                    this.LastSessionTime.Equals(other.LastSessionTime)
                ) && 
                (
                    this.FailedPasswords == other.FailedPasswords ||
                    this.FailedPasswords != null &&
                    this.FailedPasswords.Equals(other.FailedPasswords)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.LastSessionTime != null)
                    hash = hash * 59 + this.LastSessionTime.GetHashCode();
                if (this.FailedPasswords != null)
                    hash = hash * 59 + this.FailedPasswords.GetHashCode();
                return hash;
            }
        }
    }

}
