/* 
 * Tradovate API
 *
 * A motivational message should be here.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.Services.Api;
using Tradovate.Services.Model;
using Tradovate.Services.Client;
using System.Reflection;

namespace Tradovate.Services.Test
{
    /// <summary>
    ///  Class for testing Account
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountTests
    {
        // TODO uncomment below to declare an instance variable for Account
        //private Account instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Account
            //instance = new Account();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Account
        /// </summary>
        [Test]
        public void AccountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Account
            //Assert.IsInstanceOfType<Account> (instance, "variable 'instance' is a Account");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Test]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'ClearingHouseId'
        /// </summary>
        [Test]
        public void ClearingHouseIdTest()
        {
            // TODO unit test for the property 'ClearingHouseId'
        }
        /// <summary>
        /// Test the property 'RiskCategoryId'
        /// </summary>
        [Test]
        public void RiskCategoryIdTest()
        {
            // TODO unit test for the property 'RiskCategoryId'
        }
        /// <summary>
        /// Test the property 'AutoLiqProfileId'
        /// </summary>
        [Test]
        public void AutoLiqProfileIdTest()
        {
            // TODO unit test for the property 'AutoLiqProfileId'
        }
        /// <summary>
        /// Test the property 'CftcNumber'
        /// </summary>
        [Test]
        public void CftcNumberTest()
        {
            // TODO unit test for the property 'CftcNumber'
        }
        /// <summary>
        /// Test the property 'MarginAccountType'
        /// </summary>
        [Test]
        public void MarginAccountTypeTest()
        {
            // TODO unit test for the property 'MarginAccountType'
        }
        /// <summary>
        /// Test the property 'LegalStatus'
        /// </summary>
        [Test]
        public void LegalStatusTest()
        {
            // TODO unit test for the property 'LegalStatus'
        }

    }

}
