/* 
 * Tradovate API
 *
 * A motivational message should be here.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.Services.Api;
using Tradovate.Services.Model;
using Tradovate.Services.Client;
using System.Reflection;

namespace Tradovate.Services.Test
{
    /// <summary>
    ///  Class for testing CashBalanceSnapshot
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CashBalanceSnapshotTests
    {
        // TODO uncomment below to declare an instance variable for CashBalanceSnapshot
        //private CashBalanceSnapshot instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CashBalanceSnapshot
            //instance = new CashBalanceSnapshot();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CashBalanceSnapshot
        /// </summary>
        [Test]
        public void CashBalanceSnapshotInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CashBalanceSnapshot
            //Assert.IsInstanceOfType<CashBalanceSnapshot> (instance, "variable 'instance' is a CashBalanceSnapshot");
        }

        /// <summary>
        /// Test the property 'ErrorText'
        /// </summary>
        [Test]
        public void ErrorTextTest()
        {
            // TODO unit test for the property 'ErrorText'
        }
        /// <summary>
        /// Test the property 'TotalCashValue'
        /// </summary>
        [Test]
        public void TotalCashValueTest()
        {
            // TODO unit test for the property 'TotalCashValue'
        }
        /// <summary>
        /// Test the property 'TotalPnL'
        /// </summary>
        [Test]
        public void TotalPnLTest()
        {
            // TODO unit test for the property 'TotalPnL'
        }
        /// <summary>
        /// Test the property 'InitialMargin'
        /// </summary>
        [Test]
        public void InitialMarginTest()
        {
            // TODO unit test for the property 'InitialMargin'
        }
        /// <summary>
        /// Test the property 'MaintenanceMargin'
        /// </summary>
        [Test]
        public void MaintenanceMarginTest()
        {
            // TODO unit test for the property 'MaintenanceMargin'
        }
        /// <summary>
        /// Test the property 'NetLiq'
        /// </summary>
        [Test]
        public void NetLiqTest()
        {
            // TODO unit test for the property 'NetLiq'
        }

    }

}
