/* 
 * Tradovate API
 *
 * A motivational message should be here.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.Services.Api;
using Tradovate.Services.Model;
using Tradovate.Services.Client;
using System.Reflection;

namespace Tradovate.Services.Test
{
    /// <summary>
    ///  Class for testing CommandResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CommandResultTests
    {
        // TODO uncomment below to declare an instance variable for CommandResult
        //private CommandResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CommandResult
            //instance = new CommandResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CommandResult
        /// </summary>
        [Test]
        public void CommandResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CommandResult
            //Assert.IsInstanceOfType<CommandResult> (instance, "variable 'instance' is a CommandResult");
        }

        /// <summary>
        /// Test the property 'FailureReason'
        /// </summary>
        [Test]
        public void FailureReasonTest()
        {
            // TODO unit test for the property 'FailureReason'
        }
        /// <summary>
        /// Test the property 'FailureText'
        /// </summary>
        [Test]
        public void FailureTextTest()
        {
            // TODO unit test for the property 'FailureText'
        }
        /// <summary>
        /// Test the property 'CommandId'
        /// </summary>
        [Test]
        public void CommandIdTest()
        {
            // TODO unit test for the property 'CommandId'
        }

    }

}
