/* 
 * Tradovate API
 *
 * A motivational message should be here.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.Services.Api;
using Tradovate.Services.Model;
using Tradovate.Services.Client;
using System.Reflection;

namespace Tradovate.Services.Test
{
    /// <summary>
    ///  Class for testing ModifyOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModifyOrderTests
    {
        // TODO uncomment below to declare an instance variable for ModifyOrder
        //private ModifyOrder instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModifyOrder
            //instance = new ModifyOrder();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModifyOrder
        /// </summary>
        [Test]
        public void ModifyOrderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModifyOrder
            //Assert.IsInstanceOfType<ModifyOrder> (instance, "variable 'instance' is a ModifyOrder");
        }

        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'ClOrdId'
        /// </summary>
        [Test]
        public void ClOrdIdTest()
        {
            // TODO unit test for the property 'ClOrdId'
        }
        /// <summary>
        /// Test the property 'OrderQty'
        /// </summary>
        [Test]
        public void OrderQtyTest()
        {
            // TODO unit test for the property 'OrderQty'
        }
        /// <summary>
        /// Test the property 'OrderType'
        /// </summary>
        [Test]
        public void OrderTypeTest()
        {
            // TODO unit test for the property 'OrderType'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'StopPrice'
        /// </summary>
        [Test]
        public void StopPriceTest()
        {
            // TODO unit test for the property 'StopPrice'
        }
        /// <summary>
        /// Test the property 'MaxShow'
        /// </summary>
        [Test]
        public void MaxShowTest()
        {
            // TODO unit test for the property 'MaxShow'
        }
        /// <summary>
        /// Test the property 'PegDifference'
        /// </summary>
        [Test]
        public void PegDifferenceTest()
        {
            // TODO unit test for the property 'PegDifference'
        }
        /// <summary>
        /// Test the property 'TimeInForce'
        /// </summary>
        [Test]
        public void TimeInForceTest()
        {
            // TODO unit test for the property 'TimeInForce'
        }
        /// <summary>
        /// Test the property 'ExpireTime'
        /// </summary>
        [Test]
        public void ExpireTimeTest()
        {
            // TODO unit test for the property 'ExpireTime'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'ActivationTime'
        /// </summary>
        [Test]
        public void ActivationTimeTest()
        {
            // TODO unit test for the property 'ActivationTime'
        }

    }

}
