/* 
 * Tradovate API
 *
 * A motivational message should be here.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.Services.Api;
using Tradovate.Services.Model;
using Tradovate.Services.Client;
using System.Reflection;

namespace Tradovate.Services.Test
{
    /// <summary>
    ///  Class for testing NewsStory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NewsStoryTests
    {
        // TODO uncomment below to declare an instance variable for NewsStory
        //private NewsStory instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewsStory
            //instance = new NewsStory();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewsStory
        /// </summary>
        [Test]
        public void NewsStoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewsStory
            //Assert.IsInstanceOfType<NewsStory> (instance, "variable 'instance' is a NewsStory");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Test]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Test]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Teaser'
        /// </summary>
        [Test]
        public void TeaserTest()
        {
            // TODO unit test for the property 'Teaser'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Test]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }
        /// <summary>
        /// Test the property 'Channels'
        /// </summary>
        [Test]
        public void ChannelsTest()
        {
            // TODO unit test for the property 'Channels'
        }
        /// <summary>
        /// Test the property 'Stocks'
        /// </summary>
        [Test]
        public void StocksTest()
        {
            // TODO unit test for the property 'Stocks'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

    }

}
