/* 
 * Tradovate API
 *
 * A motivational message should be here.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.Services.Api;
using Tradovate.Services.Model;
using Tradovate.Services.Client;
using System.Reflection;

namespace Tradovate.Services.Test
{
    /// <summary>
    ///  Class for testing OpenDemoAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OpenDemoAccountTests
    {
        // TODO uncomment below to declare an instance variable for OpenDemoAccount
        //private OpenDemoAccount instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OpenDemoAccount
            //instance = new OpenDemoAccount();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OpenDemoAccount
        /// </summary>
        [Test]
        public void OpenDemoAccountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OpenDemoAccount
            //Assert.IsInstanceOfType<OpenDemoAccount> (instance, "variable 'instance' is a OpenDemoAccount");
        }

        /// <summary>
        /// Test the property 'TemplateAccountId'
        /// </summary>
        [Test]
        public void TemplateAccountIdTest()
        {
            // TODO unit test for the property 'TemplateAccountId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'InitialBalance'
        /// </summary>
        [Test]
        public void InitialBalanceTest()
        {
            // TODO unit test for the property 'InitialBalance'
        }

    }

}
