/* 
 * Tradovate API
 *
 * A motivational message should be here.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.Services.Api;
using Tradovate.Services.Model;
using Tradovate.Services.Client;
using System.Reflection;

namespace Tradovate.Services.Test
{
    /// <summary>
    ///  Class for testing UserAccountAutoLiq
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserAccountAutoLiqTests
    {
        // TODO uncomment below to declare an instance variable for UserAccountAutoLiq
        //private UserAccountAutoLiq instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserAccountAutoLiq
            //instance = new UserAccountAutoLiq();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserAccountAutoLiq
        /// </summary>
        [Test]
        public void UserAccountAutoLiqInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserAccountAutoLiq
            //Assert.IsInstanceOfType<UserAccountAutoLiq> (instance, "variable 'instance' is a UserAccountAutoLiq");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'MarginPercentageAlert'
        /// </summary>
        [Test]
        public void MarginPercentageAlertTest()
        {
            // TODO unit test for the property 'MarginPercentageAlert'
        }
        /// <summary>
        /// Test the property 'DailyLossPercentageAlert'
        /// </summary>
        [Test]
        public void DailyLossPercentageAlertTest()
        {
            // TODO unit test for the property 'DailyLossPercentageAlert'
        }
        /// <summary>
        /// Test the property 'DailyLossAlert'
        /// </summary>
        [Test]
        public void DailyLossAlertTest()
        {
            // TODO unit test for the property 'DailyLossAlert'
        }
        /// <summary>
        /// Test the property 'MarginPercentageLiqOnly'
        /// </summary>
        [Test]
        public void MarginPercentageLiqOnlyTest()
        {
            // TODO unit test for the property 'MarginPercentageLiqOnly'
        }
        /// <summary>
        /// Test the property 'DailyLossPercentageLiqOnly'
        /// </summary>
        [Test]
        public void DailyLossPercentageLiqOnlyTest()
        {
            // TODO unit test for the property 'DailyLossPercentageLiqOnly'
        }
        /// <summary>
        /// Test the property 'DailyLossLiqOnly'
        /// </summary>
        [Test]
        public void DailyLossLiqOnlyTest()
        {
            // TODO unit test for the property 'DailyLossLiqOnly'
        }
        /// <summary>
        /// Test the property 'MarginPercentageAutoLiq'
        /// </summary>
        [Test]
        public void MarginPercentageAutoLiqTest()
        {
            // TODO unit test for the property 'MarginPercentageAutoLiq'
        }
        /// <summary>
        /// Test the property 'DailyLossPercentageAutoLiq'
        /// </summary>
        [Test]
        public void DailyLossPercentageAutoLiqTest()
        {
            // TODO unit test for the property 'DailyLossPercentageAutoLiq'
        }
        /// <summary>
        /// Test the property 'DailyLossAutoLiq'
        /// </summary>
        [Test]
        public void DailyLossAutoLiqTest()
        {
            // TODO unit test for the property 'DailyLossAutoLiq'
        }

    }

}
